name: Release and Publish

on:
  release:
    types: [published]

jobs:
  publish-to-repo:
    uses: jerobas/arch-repo/.github/workflows/publish.yml@main
    with:
      release_repo: jerobas/territo
      release_tag: ${{ github.event.release.tag_name }}
    secrets:
      GH_PAT: ${{ secrets.GH_TOKEN }}
