name: Release Territo Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare GitHub release tag variable
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary and release
        run: |
          go build -buildvcs=false -o territo
          gh release create "${{ steps.vars.outputs.TAG }}" --generate-notes territo
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build arch packages
        uses: jerobas/arch-repo/.github/workflows/build.yml@main

      - name: Release packages
        run: |
          gh release upload "${{ steps.vars.outputs.TAG }}" dist/*
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Add packages to arch repo
        uses: jerobas/arch-repo/.github/workflows/publish.yml@main
        with:
          release_repo: jerobas/territo
          release_tag: ${{ steps.vars.outputs.TAG }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}