name: Release Territo Binary

on:
  push:
    tags:
      - 'v*'  # Only run when a tag like v1.0, v2.0.1, etc. is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Or 1.24 if you prefer

      - name: Build binary and release
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          go build -o territo
          gh release create $latest_tag --generate-notes territo
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
